package com.google.android.gms.internal;

import android.content.Context;
import android.content.SharedPreferences;
import com.WaTF.WaTFBank.BuildConfig;
import java.util.List;
import java.util.concurrent.TimeUnit;
import net.sqlcipher.database.SQLiteDatabase;
import org.json.JSONObject;
/* JADX WARN: Classes with same name are omitted:
  assets/classes2.dex
 */
@zzzv
/* loaded from: classes.dex */
public final class zznh {
    private static zzmx<String> zzbhl = zzmx.zza(0, "gads:sdk_core_experiment_id");
    public static final zzmx<String> zzbhm = zzmx.zza(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    private static zzmx<String> zzbhn = zzmx.zza(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    private static zzmx<Boolean> zzbho = zzmx.zza(0, "gads:request_builder:singleton_webview", (Boolean) false);
    private static zzmx<String> zzbhp = zzmx.zza(0, "gads:request_builder:singleton_webview_experiment_id");
    private static zzmx<Boolean> zzbhq = zzmx.zza(0, "gads:sdk_use_dynamic_module", (Boolean) true);
    private static zzmx<String> zzbhr = zzmx.zza(0, "gads:sdk_use_dynamic_module_experiment_id");
    public static final zzmx<Boolean> zzbhs = zzmx.zza(0, "gads:sdk_crash_report_enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbht = zzmx.zza(0, "gads:sdk_crash_report_full_stacktrace", (Boolean) false);
    public static final zzmx<String> zzbhu = zzmx.zza(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final zzmx<Boolean> zzbhv = zzmx.zza(0, "gads:block_autoclicks", (Boolean) false);
    private static zzmx<String> zzbhw = zzmx.zza(0, "gads:block_autoclicks_experiment_id");
    private static zzmx<String> zzbhx = zzmx.zza(0, "gads:spam_app_context:experiment_id");
    private static zzmx<Integer> zzbhy = zzmx.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzmx<String> zzbhz = zzmx.zza(1, "gads:video_exo_player:version", "1");
    public static final zzmx<Integer> zzbia = zzmx.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzmx<Integer> zzbib = zzmx.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzmx<Integer> zzbic = zzmx.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    private static zzmx<String> zzbid = zzmx.zza(0, "gads:video_stream_cache:experiment_id");
    public static final zzmx<Integer> zzbie = zzmx.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzmx<Integer> zzbif = zzmx.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzmx<Integer> zzbig = zzmx.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzmx<Long> zzbih = zzmx.zza(1, "gads:video_stream_cache:limit_time_sec", 300L);
    public static final zzmx<Long> zzbii = zzmx.zza(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    public static final zzmx<Integer> zzbij = zzmx.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzmx<Boolean> zzbik = zzmx.zza(0, "gads:video:metric_reporting_enabled", (Boolean) false);
    public static final zzmx<String> zzbil = zzmx.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzmx<Long> zzbim = zzmx.zza(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    public static final zzmx<Boolean> zzbin = zzmx.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzmx<Long> zzbio = zzmx.zza(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    public static final zzmx<Boolean> zzbip = zzmx.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzmx<Integer> zzbiq = zzmx.zza(1, "gads:video:spinner:scale", 4);
    public static final zzmx<Long> zzbir = zzmx.zza(1, "gads:video:spinner:jank_threshold_ms", 50L);
    public static final zzmx<Boolean> zzbis = zzmx.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzmx<Boolean> zzbit = zzmx.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzmx<Boolean> zzbiu = zzmx.zza(1, "gads:memory_bundle:runtime_info", (Boolean) true);
    public static final zzmx<String> zzbiv = zzmx.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzmx<Integer> zzbiw = zzmx.zza(1, "gads:video:codec_query_minimum_version", 16);
    private static zzmx<Boolean> zzbix = zzmx.zza(0, "gads:ad_id_app_context:enabled", (Boolean) false);
    private static zzmx<Float> zzbiy = zzmx.zza(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
    private static zzmx<String> zzbiz = zzmx.zza(0, "gads:ad_id_app_context:experiment_id");
    private static zzmx<String> zzbja = zzmx.zza(0, "gads:ad_id_use_shared_preference:experiment_id");
    private static zzmx<Boolean> zzbjb = zzmx.zza(0, "gads:ad_id_use_shared_preference:enabled", (Boolean) false);
    private static zzmx<Float> zzbjc = zzmx.zza(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
    private static zzmx<Boolean> zzbjd = zzmx.zza(0, "gads:ad_id_use_persistent_service:enabled", (Boolean) false);
    private static zzmx<String> zzbje = zzmx.zzb(0, "gads:looper_for_gms_client:experiment_id");
    public static final zzmx<Boolean> zzbjf = zzmx.zza(0, "gads:looper_for_gms_client:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbjg = zzmx.zza(0, "gads:sw_ad_request_service:enabled", (Boolean) true);
    private static zzmx<Boolean> zzbjh = zzmx.zza(0, "gads:sw_dynamite:enabled", (Boolean) true);
    public static final zzmx<String> zzbji = zzmx.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    public static final zzmx<String> zzbjj = zzmx.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    public static final zzmx<String> zzbjk = zzmx.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    public static final zzmx<Boolean> zzbjl = zzmx.zza(0, "gads:enabled_sdk_csi", (Boolean) false);
    public static final zzmx<String> zzbjm = zzmx.zza(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    public static final zzmx<Boolean> zzbjn = zzmx.zza(0, "gads:sdk_csi_write_to_file", (Boolean) false);
    public static final zzmx<Boolean> zzbjo = zzmx.zza(0, "gads:enable_content_fetching", (Boolean) true);
    public static final zzmx<Integer> zzbjp = zzmx.zza(0, "gads:content_length_weight", 1);
    public static final zzmx<Integer> zzbjq = zzmx.zza(0, "gads:content_age_weight", 1);
    public static final zzmx<Integer> zzbjr = zzmx.zza(0, "gads:min_content_len", 11);
    public static final zzmx<Integer> zzbjs = zzmx.zza(0, "gads:fingerprint_number", 10);
    public static final zzmx<Integer> zzbjt = zzmx.zza(0, "gads:sleep_sec", 10);
    public static final zzmx<Boolean> zzbju = zzmx.zza(1, "gads:enable_content_url_hash", (Boolean) true);
    public static final zzmx<Integer> zzbjv = zzmx.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzmx<Boolean> zzbjw = zzmx.zza(1, "gads:enable_content_vertical_hash", (Boolean) true);
    public static final zzmx<Integer> zzbjx = zzmx.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzmx<Integer> zzbjy = zzmx.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzmx<String> zzbjz = zzmx.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzmx<String> zzbka = zzmx.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzmx<Boolean> zzbkb = zzmx.zza(0, "gad:app_index_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkc = zzmx.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzmx<Boolean> zzbkd = zzmx.zza(0, "gads:app_index:without_content_info_present:enabled", (Boolean) true);
    public static final zzmx<Long> zzbke = zzmx.zza(0, "gads:app_index:timeout_ms", 1000L);
    private static zzmx<String> zzbkf = zzmx.zza(0, "gads:app_index:experiment_id");
    private static zzmx<String> zzbkg = zzmx.zza(0, "gads:kitkat_interstitial_workaround:experiment_id");
    public static final zzmx<Boolean> zzbkh = zzmx.zza(0, "gads:kitkat_interstitial_workaround:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbki = zzmx.zza(0, "gads:interstitial_follow_url", (Boolean) true);
    public static final zzmx<Boolean> zzbkj = zzmx.zza(0, "gads:interstitial_follow_url:register_click", (Boolean) true);
    private static zzmx<String> zzbkk = zzmx.zza(0, "gads:interstitial_follow_url:experiment_id");
    private static zzmx<Boolean> zzbkl = zzmx.zza(0, "gads:analytics_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkm = zzmx.zza(0, "gads:ad_key_enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbkn = zzmx.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbko = zzmx.zza(1, "gads:sai:banner_ad_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkp = zzmx.zza(1, "gads:sai:native_ad_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkq = zzmx.zza(1, "gads:sai:interstitial_ad_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkr = zzmx.zza(1, "gads:sai:rewardedvideo_ad_enabled", (Boolean) true);
    public static final zzmx<String> zzbks = zzmx.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzmx<String> zzbkt = zzmx.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    public static final zzmx<Boolean> zzbku = zzmx.zza(1, "gads:sai:click_gmsg_enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbkv = zzmx.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzmx<String> zzbkw = zzmx.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzmx<Long> zzbkx = zzmx.zza(1, "gads:sai:timeout_ms", -1L);
    public static final zzmx<Integer> zzbky = zzmx.zza(1, "gads:sai:scion_thread_pool_size", 5);
    private static zzmx<Integer> zzbkz = zzmx.zza(0, "gads:webview_cache_version", 0);
    public static final zzmx<Boolean> zzbla = zzmx.zza(1, "gads:webview:ignore_over_scroll", (Boolean) true);
    private static zzmx<String> zzblb = zzmx.zzb(0, "gads:pan:experiment_id");
    public static final zzmx<Boolean> zzblc = zzmx.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    public static final zzmx<Long> zzbld = zzmx.zza(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    public static final zzmx<Boolean> zzble = zzmx.zza(1, "gads:app_activity_tracker:enabled", (Boolean) true);
    public static final zzmx<Long> zzblf = zzmx.zza(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    public static final zzmx<Long> zzblg = zzmx.zza(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzmx<Boolean> zzblh = zzmx.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzmx<Long> zzbli = zzmx.zza(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    public static final zzmx<Boolean> zzblj = zzmx.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzmx<Boolean> zzblk = zzmx.zza(1, "gads:enable_ad_loader_manager", (Boolean) true);
    private static zzmx<Boolean> zzbll = zzmx.zza(0, "gads:ad_serving:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzblm = zzmx.zza(1, "gads:ad_manager_enforce_arp_invariant:enabled", (Boolean) false);
    public static final zzmx<Long> zzbln = zzmx.zza(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    public static final zzmx<Boolean> zzblo = zzmx.zza(1, "gads:interstitial_ad_immersive_mode", (Boolean) true);
    public static final zzmx<Boolean> zzblp = zzmx.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    private static zzmx<Boolean> zzblq = zzmx.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static zzmx<String> zzblr = zzmx.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static zzmx<Integer> zzbls = zzmx.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static zzmx<Integer> zzblt = zzmx.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzmx<Boolean> zzblu = zzmx.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzblv = zzmx.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    public static final zzmx<String> zzblw = zzmx.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    public static final zzmx<String> zzblx = zzmx.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    public static final zzmx<Integer> zzbly = zzmx.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    public static final zzmx<Integer> zzblz = zzmx.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    public static final zzmx<Integer> zzbma = zzmx.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    public static final zzmx<String> zzbmb = zzmx.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    public static final zzmx<Integer> zzbmc = zzmx.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    public static final zzmx<Integer> zzbmd = zzmx.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    public static final zzmx<Long> zzbme = zzmx.zza(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    public static final zzmx<Long> zzbmf = zzmx.zza(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    public static final zzmx<Float> zzbmg = zzmx.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    public static final zzmx<Float> zzbmh = zzmx.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzmx<Boolean> zzbmi = zzmx.zza(0, "gads:debug_logging_feature:enable", (Boolean) false);
    public static final zzmx<Boolean> zzbmj = zzmx.zza(0, "gads:debug_logging_feature:intercept_web_view", (Boolean) false);
    private static zzmx<Integer> zzbmk = zzmx.zza(1, "gads:heap_wastage:bytes", 0);
    public static final zzmx<String> zzbml = zzmx.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzmx<String> zzbmm = zzmx.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzmx<Boolean> zzbmn = zzmx.zza(0, "gads:log:verbose_enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbmo = zzmx.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzmx<Long> zzbmp = zzmx.zza(1, "gads:position_watcher:throttle_ms", 200L);
    public static final zzmx<Boolean> zzbmq = zzmx.zza(1, "gads:include_lock_screen_apps_for_visibility", (Boolean) true);
    public static final zzmx<Boolean> zzbmr = zzmx.zza(0, "gads:device_info_caching:enabled", (Boolean) true);
    public static final zzmx<Long> zzbms = zzmx.zza(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    public static final zzmx<Boolean> zzbmt = zzmx.zza(0, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbmu = zzmx.zza(0, "gads:webview:error_reporting_enabled", (Boolean) false);
    private static zzmx<Boolean> zzbmv = zzmx.zza(0, "gads:adid_reporting:enabled", (Boolean) false);
    private static zzmx<Boolean> zzbmw = zzmx.zza(0, "gads:ad_settings_page_reporting:enabled", (Boolean) false);
    private static zzmx<Boolean> zzbmx = zzmx.zza(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", (Boolean) false);
    private static zzmx<Boolean> zzbmy = zzmx.zza(0, "gads:request_pkg:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbmz = zzmx.zza(1, "gads:gmsg:disable_back_button:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbna = zzmx.zza(0, "gads:gmsg:video_meta:enabled", (Boolean) true);
    private static zzmx<String> zzbnb = zzmx.zza(0, "gads:gmsg:video_meta:experiment_id");
    private static zzmx<Long> zzbnc = zzmx.zza(1, "gads:network:cache_prediction_duration_s", 300L);
    public static final zzmx<Long> zzbnd = zzmx.zza(1, "gads:network:network_prediction_timeout_ms", 2000L);
    public static final zzmx<Boolean> zzbne = zzmx.zza(0, "gads:mediation:dynamite_first:admobadapter", (Boolean) true);
    public static final zzmx<Boolean> zzbnf = zzmx.zza(0, "gads:mediation:dynamite_first:adurladapter", (Boolean) true);
    public static final zzmx<Boolean> zzbng = zzmx.zza(1, "gads:bypass_adrequest_service_for_inlined_mediation", (Boolean) true);
    public static final zzmx<Long> zzbnh = zzmx.zza(0, "gads:resolve_future:default_timeout_ms", 30000L);
    public static final zzmx<Long> zzbni = zzmx.zza(0, "gads:ad_loader:timeout_ms", 60000L);
    public static final zzmx<Long> zzbnj = zzmx.zza(0, "gads:rendering:timeout_ms", 60000L);
    public static final zzmx<Boolean> zzbnk = zzmx.zza(0, "gads:adshield:enable_adshield_instrumentation", (Boolean) false);
    public static final zzmx<Long> zzbnl = zzmx.zza(1, "gads:gestures:task_timeout", 2000L);
    public static final zzmx<Boolean> zzbnm = zzmx.zza(1, "gads:gestures:btt:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbnn = zzmx.zza(1, "gads:gestures:sss:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbno = zzmx.zza(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbnp = zzmx.zza(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final zzmx<Integer> zzbnq = zzmx.zza(1, "gads:gestures:ts", 1);
    public static final zzmx<Boolean> zzbnr = zzmx.zza(1, "gads:gestures:tdvs:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbns = zzmx.zza(1, "gads:gestures:tvvs:enabled", (Boolean) false);
    public static final zzmx<String> zzbnt = zzmx.zza(1, "gads:gestures:pk", "");
    public static final zzmx<Boolean> zzbnu = zzmx.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbnv = zzmx.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbnw = zzmx.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbnx = zzmx.zza(0, "gass:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbny = zzmx.zza(0, "gass:enable_int_signal", (Boolean) true);
    public static final zzmx<Boolean> zzbnz = zzmx.zza(0, "gass:enable_ad_attestation_signal", (Boolean) true);
    private static zzmx<Boolean> zzboa = zzmx.zza(0, "gads:adid_notification:first_party_check:enabled", (Boolean) true);
    private static zzmx<Boolean> zzbob = zzmx.zza(0, "gads:edu_device_helper:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzboc = zzmx.zza(0, "gads:support_screen_shot", (Boolean) true);
    public static final zzmx<Boolean> zzbod = zzmx.zza(0, "gads:use_get_drawing_cache_for_screenshot:enabled", (Boolean) true);
    private static zzmx<String> zzboe = zzmx.zza(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    private static zzmx<String> zzbof = zzmx.zza(1, "gads:sdk_core_constants:experiment_id");
    public static final zzmx<String> zzbog = zzmx.zza(1, "gads:sdk_core_constants:caps", "");
    public static final zzmx<Long> zzboh = zzmx.zza(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
    public static final zzmx<Boolean> zzboi = zzmx.zza(0, "gads:js_flags:mf", (Boolean) false);
    private static zzmx<Boolean> zzboj = zzmx.zza(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final zzmx<Boolean> zzbok = zzmx.zza(0, "gads:custom_render:ping_on_ad_rendered", (Boolean) false);
    public static final zzmx<String> zzbol = zzmx.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static zzmx<String> zzbom = zzmx.zza(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    private static zzmx<String> zzbon = zzmx.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzmx<String> zzboo = zzmx.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    private static zzmx<String> zzbop = zzmx.zza(1, "gads:singleton_webview_native:experiment_id");
    public static final zzmx<Boolean> zzboq = zzmx.zza(1, "gads:enable_untrack_view_native", (Boolean) true);
    public static final zzmx<Boolean> zzbor = zzmx.zza(1, "gads:ignore_untrack_view_google_native", (Boolean) true);
    public static final zzmx<Boolean> zzbos = zzmx.zza(1, "gads:reset_listeners_preparead_native", (Boolean) true);
    public static final zzmx<Integer> zzbot = zzmx.zza(1, "gads:native_video_load_timeout", 10);
    public static final zzmx<String> zzbou = zzmx.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzmx<Boolean> zzbov = zzmx.zza(1, "gads:clamp_native_video_player_dimensions", (Boolean) true);
    public static final zzmx<Boolean> zzbow = zzmx.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzmx<Boolean> zzbox = zzmx.zza(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final zzmx<Boolean> zzboy = zzmx.zza(1, "gads:native:overlay_new_fix:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzboz = zzmx.zza(1, "gads:native:count_impression_for_assets", (Boolean) false);
    public static final zzmx<Boolean> zzbpa = zzmx.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    public static final zzmx<Boolean> zzbpb = zzmx.zza(0, "gads:method_tracing:enabled", (Boolean) false);
    public static final zzmx<Long> zzbpc = zzmx.zza(0, "gads:method_tracing:duration_ms", 30000L);
    public static final zzmx<Integer> zzbpd = zzmx.zza(0, "gads:method_tracing:count", 5);
    public static final zzmx<Integer> zzbpe = zzmx.zza(0, "gads:method_tracing:filesize", 134217728);
    private static zzmx<Boolean> zzbpf = zzmx.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static zzmx<String> zzbpg = zzmx.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzmx<Long> zzbph = zzmx.zza(1, "gads:auto_location_timeout", 2000L);
    private static zzmx<String> zzbpi = zzmx.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static zzmx<Long> zzbpj = zzmx.zza(1, "gads:auto_location_interval", -1L);
    private static zzmx<String> zzbpk = zzmx.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzmx<Boolean> zzbpl = zzmx.zza(1, "gads:fetch_app_settings_using_cld:enabled", (Boolean) false);
    private static zzmx<String> zzbpm = zzmx.zza(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    public static final zzmx<Long> zzbpn = zzmx.zza(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    private static zzmx<String> zzbpo = zzmx.zza(0, "gads:afs:csa:experiment_id");
    public static final zzmx<String> zzbpp = zzmx.zza(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    public static final zzmx<String> zzbpq = zzmx.zza(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    public static final zzmx<String> zzbpr = zzmx.zza(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    public static final zzmx<String> zzbps = zzmx.zza(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    public static final zzmx<String> zzbpt = zzmx.zza(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    public static final zzmx<Long> zzbpu = zzmx.zza(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    private static zzmx<Boolean> zzbpv = zzmx.zza(0, "gads:afs:csa_ad_manager_enabled", (Boolean) true);
    private static zzmx<Boolean> zzbpw = zzmx.zza(1, "gads:parental_controls:send_from_client", (Boolean) true);
    private static zzmx<Boolean> zzbpx = zzmx.zza(1, "gads:parental_controls:cache_results", (Boolean) true);
    public static final zzmx<Long> zzbpy = zzmx.zza(1, "gads:parental_controls:timeout", 2000L);
    private static zzmx<String> zzbpz = zzmx.zza(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    private static zzmx<Long> zzbqa = zzmx.zza(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    public static final zzmx<Boolean> zzbqb = zzmx.zza(0, "gads:safe_browsing:debug", (Boolean) false);
    public static final zzmx<Boolean> zzbqc = zzmx.zza(0, "gads:webview_cookie:enabled", (Boolean) true);
    private static zzmx<Integer> zzbqd = zzmx.zza(1, "gads:cache:ad_request_timeout_millis", (int) SQLiteDatabase.MAX_SQL_CACHE_SIZE);
    private static zzmx<Integer> zzbqe = zzmx.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static zzmx<Long> zzbqf = zzmx.zza(1, "gads:cache:javascript_timeout_millis", 5000L);
    public static final zzmx<Boolean> zzbqg = zzmx.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzmx<Boolean> zzbqh = zzmx.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzmx<Boolean> zzbqi = zzmx.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzmx<Long> zzbqj = zzmx.zza(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzmx<Boolean> zzbqk = zzmx.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    private static zzmx<Boolean> zzbql = zzmx.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    private static zzmx<Long> zzbqm = zzmx.zza(1, "gads:cache:connection_timeout", 5000L);
    private static zzmx<Long> zzbqn = zzmx.zza(1, "gads:cache:read_only_connection_timeout", 5000L);
    public static final zzmx<Boolean> zzbqo = zzmx.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzmx<String> zzbqp = zzmx.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzmx<Integer> zzbqq = zzmx.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzmx<Boolean> zzbqr = zzmx.zza(1, "gads:chrome_custom_tabs:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbqs = zzmx.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbqt = zzmx.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzmx<Boolean> zzbqu = zzmx.zza(1, "gads:drx_in_app_preview:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbqv = zzmx.zza(1, "gads:drx_debug_signals:enabled", (Boolean) true);
    public static final zzmx<String> zzbqw = zzmx.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzmx<String> zzbqx = zzmx.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzmx<String> zzbqy = zzmx.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzmx<String> zzbqz = zzmx.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzmx<Integer> zzbra = zzmx.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzmx<Integer> zzbrb = zzmx.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzmx<Boolean> zzbrc = zzmx.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzmx<Boolean> zzbrd = zzmx.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzmx<Integer> zzbre = zzmx.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzmx<Boolean> zzbrf = zzmx.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzmx<Boolean> zzbrg = zzmx.zza(0, "gad:force_local_ad_request_service:enabled", (Boolean) false);
    public static final zzmx<Integer> zzbrh = zzmx.zza(1, "gad:http_redirect_max_count:times", 8);
    private static zzmx<Boolean> zzbri = zzmx.zza(0, "gads:nonagon:red_button", (Boolean) false);
    private static zzmx<Boolean> zzbrj = zzmx.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static zzmx<String> zzbrk = zzmx.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> zzbrl = zzmx.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static zzmx<String> zzbrm = zzmx.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> zzbrn = zzmx.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    private static zzmx<Boolean> zzbro = zzmx.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    private static zzmx<String> zzbrp = zzmx.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> zzbrq = zzmx.zza(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static zzmx<String> zzbrr = zzmx.zza(1, "gads:nonagon:nativead:ad_unit_exclusions", "(?!)");
    private static zzmx<Boolean> zzbrs = zzmx.zza(1, "gads:nonagon:service:enabled", (Boolean) false);
    public static final zzmx<Long> zzbrt = zzmx.zza(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    public static final zzmx<String> zzbru = zzmx.zza(0, "gads:public_beta:traffic_multiplier", BuildConfig.VERSION_NAME);
    public static final zzmx<Boolean> zzbrv = zzmx.zza(1, "gads:real_test_request:enabled", (Boolean) true);
    public static final zzmx<Boolean> zzbrw = zzmx.zza(1, "gads:real_test_request:render_webview_label", (Boolean) true);
    public static final zzmx<Boolean> zzbrx = zzmx.zza(1, "gads:real_test_request:render_native_label", (Boolean) true);
    private static byte[] zzbry;

    public static void initialize(Context context) {
        zzajk.zza(context, new zzni(context));
        int intValue = ((Integer) zzkb.zzif().zzd(zzbmk)).intValue();
        if (intValue <= 0 || zzbry != null) {
            return;
        }
        zzbry = new byte[intValue];
    }

    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzkb.zzid();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzkb.zzie().zza(edit, 1, jSONObject);
        zzkb.zzid();
        edit.commit();
    }

    public static List<String> zziw() {
        return zzkb.zzie().zziw();
    }

    public static List<String> zzix() {
        return zzkb.zzie().zzix();
    }
}
